# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    convert.csv:
        class: AppBundle\Services\ConvertCSV

    validator.csv:
        class: AppBundle\Services\ValidatorCSV
        arguments: [ "@doctrine.orm.entity_manager"]

    import.csv:
        class: AppBundle\Services\ImportCSV
        arguments: ["@service_container"]